"""signup table

Revision ID: 4c4ba04b0c24
Revises: 743120517553
Create Date: 2026-09-19 08:51:28.078787

One row per account the mock sign-up created. `email` is unique so a duplicate is refused by the
index rather than by a read the next request could race; `visitor_id` is nullable because the
funnel fails open when the visitor service is down and the purchase step must not dead-end on
it. `plan` is text under a CHECK constraint carrying the wire values (see `funnel_event.name`).

Migrations are forward-only by house policy: `downgrade` stays empty and bad state is corrected
with a new forward revision, never a rollback.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c4ba04b0c24"
down_revision: str | Sequence[str] | None = "743120517553"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "signup",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("visitor_id", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum(
                "basic", "family", name="signup_plan", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("password_was_pwned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["visitor_id"], ["visitor.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_signup_visitor_id"), "signup", ["visitor_id"], unique=False)


def downgrade() -> None:
    """Forward-only: see the module docstring. Autogenerated downgrades are deliberately dropped."""
