"""funnel_event table

Revision ID: 743120517553
Revises: 9b3f1c2d4e5a
Create Date: 2026-09-18 22:16:26.646713

One row per funnel step a visitor took. The primary key is client-minted so a retry lands on
`ON CONFLICT DO NOTHING`; `flag_key` / `variant_key` are the visitor's assignment copied in at
write time, nullable for a visitor who arrived while the flag was disabled. `name` is text under
a CHECK constraint carrying the wire values, so a new step is a constraint change and a query
outside Python reads `landing_view`, not a member name.

Migrations are forward-only by house policy: `downgrade` stays empty and bad state is corrected
with a new forward revision, never a rollback.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "743120517553"
down_revision: str | Sequence[str] | None = "9b3f1c2d4e5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "funnel_event",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("visitor_id", sa.Text(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "landing_view",
                "scan_started",
                "scan_completed",
                "cta_click",
                "signup_started",
                "activation",
                name="funnel_event_name",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("flag_key", sa.Text(), nullable=True),
        sa.Column("variant_key", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["flag_key"],
            ["feature_flag.key"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_id"],
            ["visitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funnel_event_flag_key"), "funnel_event", ["flag_key"], unique=False)
    op.create_index(
        op.f("ix_funnel_event_visitor_id"), "funnel_event", ["visitor_id"], unique=False
    )


def downgrade() -> None:
    """Forward-only: see the module docstring. Autogenerated downgrades are deliberately dropped."""
