"""feature flag and visitor tables

Revision ID: 75463482a98c
Revises: cdd9bbd45307
Create Date: 2026-09-18 17:44:45.135545

The feature flag (variants as one JSONB value, `updated_at` as the optimistic-lock token), the
visitor, and the stored assignment keyed on (visitor, flag) so a visitor holds at most one
variant per flag.

Migrations are forward-only by house policy: `downgrade` stays empty and bad state is corrected
with a new forward revision, never a rollback.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75463482a98c"
down_revision: str | Sequence[str] | None = "cdd9bbd45307"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feature_flag",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("variants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "visitor",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visitor_assignment",
        sa.Column("visitor_id", sa.Text(), nullable=False),
        sa.Column("flag_key", sa.Text(), nullable=False),
        sa.Column("variant_key", sa.Text(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flag_key"],
            ["feature_flag.key"],
        ),
        sa.ForeignKeyConstraint(
            ["visitor_id"],
            ["visitor.id"],
        ),
        sa.PrimaryKeyConstraint("visitor_id", "flag_key"),
    )


def downgrade() -> None:
    """Forward-only: see the module docstring. Autogenerated downgrades are deliberately dropped."""
