"""breach table

Revision ID: cdd9bbd45307
Revises: c1cc8cd4064e
Create Date: 2026-09-17 23:47:02.445456

The persisted HIBP catalog. Every boolean is NOT NULL so the default exclusions
(`WHERE NOT is_retired`) cannot silently drop rows through SQL's three-valued logic, and
`pwn_count` is BigInteger because the largest breach on record already sits at 91% of int4.

Migrations are forward-only by house policy: `downgrade` stays empty and bad state is corrected
with a new forward revision, never a rollback.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdd9bbd45307"
down_revision: str | Sequence[str] | None = "c1cc8cd4064e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "breach",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("breach_date", sa.Date(), nullable=False),
        sa.Column("added_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pwn_count", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("logo_path", sa.Text(), nullable=False),
        sa.Column("data_classes", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_fabricated", sa.Boolean(), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("is_retired", sa.Boolean(), nullable=False),
        sa.Column("is_spam_list", sa.Boolean(), nullable=False),
        sa.Column("is_malware", sa.Boolean(), nullable=False),
        sa.Column("is_subscription_free", sa.Boolean(), nullable=False),
        sa.Column("is_stealer_log", sa.Boolean(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("disclosure_url", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_breach_breach_date"), "breach", ["breach_date"], unique=False)
    op.create_index(
        "ix_breach_data_classes", "breach", ["data_classes"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_breach_pwn_count"), "breach", ["pwn_count"], unique=False)


def downgrade() -> None:
    """Forward-only: see the module docstring. Autogenerated downgrades are deliberately dropped."""
